### ISSUE TITLE
「エントリー」のエリアにある「エントリーはこちら」ボタンにリンクが貼られていない

### ISSUE THREAD

**Issue by hidebox** [devdrops-com/runningsakurajima.jp#11]
「エントリー」のエリアにある「エントリーはこちら」ボタンにリンクが貼られていない。
下記のそれぞれにリンクを貼る。

・ランネット
・スポーツエントリー

**Comment by hidebox** [comment]
「ランネット」のボタンのリンクを貼りました。
また、「スポーツエントリー」のボタンは、申込ページが存在しないため、disabledのクラスをつけました。

**Comment by devdrops-com** [comment]
ページが公開されたら戻す
