### ISSUE TITLE
「大会開催要項」において、「注意事項」の8.の記述がパンフレットとウェブサイトで違っている

### ISSUE THREAD

**Issue by hidebox** [devdrops-com/runningsakurajima.jp#12]
「大会開催要項」において、「注意事項」の8.の記述がパンフレットとウェブサイトで違っている。
相違点は下記の通り

▼パンフレット▼
会場での紛失等については大会事務局では責任を負いかねますので、各自の責任で管理してください。

▼ウェブサイト▼
会場での紛失等については大会事務局では責任を負いかねますので、各自の責任で管理すること。

**Comment by hidebox** [comment]
パンフレットと同じ文面に変更しました。

**Comment by devdrops-com** [comment]
おｋ
