### ISSUE TITLE
「５つのポイント」のエリアにある「よりみちクルーズ船」の説明がパンフレットとウェブサイトで違っている

### ISSUE THREAD

**Issue by hidebox** [devdrops-com/runningsakurajima.jp#9]
「５つのポイント」のエリアにある「よりみちクルーズ船」の説明がパンフレットとウェブサイトで違っている

▼パンフレット▼
 桜島と錦江湾の魅力を海上から身近に楽しむことができる桜島までの片道約50分間のプチクルーズです。

▼ウェブサイト▼
 桜島と錦江湾を眺めることがで゙きる約50分間のクルーズです。

**Comment by hidebox** [comment]
パンフレットと同じ文面を掲載しました。

**Comment by devdrops-com** [comment]
おｋ
